improves the module examples/complete
alibabacloud-automation/terraform-alicloud-ram-role pull request #7
Opened 2021-12-29 03:44 UTC by china-1947

2021-12-30 02:44 UTC, Wanghx0991 commented on examples/complete/main.tf
> +      name            = "manage-slb-and-eip-resource-006"
manage-slb-and-eip-resource

2021-12-30 02:44 UTC, Wanghx0991 commented on examples/complete/main.tf
> +      name            = "manage-slb-and-eip-resource-007"
manage-slb-and-eip-resource

2021-12-30 02:44 UTC, Wanghx0991 commented on examples/complete/tfvars/01-update.tfvars
> +    user_names = "xumingtest,nihonglei"
这些名字都换成fake的数据,可以跑通么?

2021-12-30 02:44 UTC, Wanghx0991 commented on examples/complete/variables.tf
> +  default     = "tf-test-role-004"
tf-test-role

2021-12-30 02:44 UTC, Wanghx0991 commented on examples/complete/tfvars/01-update.tfvars
> +role_name = "tf-test-role-005"
tf-test-role-update

2021-12-30 02:44 UTC, Wanghx0991 commented on examples/complete/tfvars/01-update.tfvars
> +  {
force , services这些var应该都是可改的

2022-01-06 10:57 UTC, xiaozhu36 requested changes

2022-01-06 10:57 UTC, xiaozhu36 commented on examples/complete/tfvars/01-update.tfvars
> +  },
半分review的都没有改啊，这些数据不要用现有的

2022-01-07 02:04 UTC, xiaozhu36 requested changes

2022-01-07 02:04 UTC, xiaozhu36 commented on examples/complete/variables.tf
> +  default     = true
默认值设置为 false，修改的时候修改为 true

2022-01-10 02:28 UTC, merged